### ISSUE TITLE
Failure to resolve lodash.clonedeep

### ISSUE THREAD

**Issue by ikadix** [nuxt-community/supabase-module#21]
### Version
    "@nuxtjs/supabase": "^0.1.4",
    "nuxt3": "latest"

### Reproduction Link

https://stackblitz.com/edit/github-zshr3e?file=app.vue

### Steps to reproduce

Follow the instructions to install and use from the docs. 
I have tried with yarn, npm and pnpm.

### What is Expected?

Should be able to use supabase client.

### What is actually happening?

Error log immediately on starup. 

` ERROR  Failed to resolve force included dependency: lodash.clonedeep  `

**Comment by Atinux** [comment]
Sorry about this, seems that Supabase-js removed the dependency of `lodash.clonedeep`, which is a great news 🎊  (https://github.com/supabase/realtime-js/pull/150)

It's now fixed in [v0.1.5](https://github.com/nuxt-community/supabase-module/releases/tag/v0.1.5), see demo on https://stackblitz.com/edit/github-zshr3e-hvu1qm?file=package-lock.json
